### ISSUE TITLE
isNumberBetweenInclusive returns true for -1 when lower bounds is 0

### ISSUE THREAD

**Issue by alanfinney** [SeanCannon/prettycats#2]
prr.isNumberBetweenInclusive(0, 6);
test with -1.
returns success (not expected).

test with -2
returns failure (expected).

test with 7
returns failure (expected).

**Comment by SeanCannon** [comment]
Resolved with @alanfinney that this issue was from an older release of prettycats and works as expected in the current release. Closing.
